github: Build the macOS toolchain with a stage1 Clang

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -235,8 +235,7 @@ jobs:
             llvm-mingw-linux.tar.xz
           retention-days: 7
 
-  # Build a cross compiler for macOS, targeting Windows.
-  macos:
+  macos-stage1:
     if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
     needs: [prepare]
     runs-on: macos-14
@@ -256,7 +255,51 @@ jobs:
           # form. Therefore, autodetection will pick them up, but linking
           # universal binaries fails as those libraries are unavailable in the
           # other (arm64) architecture form.
-          MACOS_REDIST=1 LLVM_CMAKEFLAGS="-DLLVM_ENABLE_ZSTD=OFF -DLLDB_ENABLE_PYTHON=OFF" ./build-all.sh $(pwd)/install/llvm-mingw
+          LLVM_CMAKEFLAGS="-DLLVM_ENABLE_ZSTD=OFF -DLLDB_ENABLE_PYTHON=OFF" ./build-llvm.sh $(pwd)/install/llvm
+          .github/workflows/store-version.sh install/llvm/versions.txt
+          cd install
+          NAME=llvm-$TAG-macos-$(uname -m)
+          mv llvm $NAME
+          gtar -Jcf ../$NAME.tar.xz --format=ustar --numeric-owner --owner=0 --group=0 --sort=name --mtime="$BUILD_DATE" $NAME
+      - uses: actions/upload-artifact@v4
+        with:
+          name: macos-llvm
+          path: |
+            llvm-*.tar.xz
+          retention-days: 7
+
+  # Build a cross compiler for macOS, targeting Windows.
+  macos:
+    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
+    needs: [prepare, macos-stage1]
+    runs-on: macos-14
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/download-artifact@v4
+        with:
+          name: macos-llvm
+      - name: Unpack stage1 Clang
+        run: |
+          tar -Jxf llvm-*.tar.xz
+          rm llvm-*.tar.xz
+          mv llvm* $HOME/llvm
+          echo $HOME/llvm/bin >> $GITHUB_PATH
+      - name: Build
+        env:
+          LLVM_VERSION: ${{needs.prepare.outputs.LLVM_VERSION}}
+          MINGW_W64_VERSION: ${{needs.prepare.outputs.MINGW_W64_VERSION}}
+          TAG: ${{needs.prepare.outputs.TAG}}
+          SOURCE_DATE_EPOCH: ${{needs.prepare.outputs.COMMIT_DATE_UNIX}}
+          BUILD_DATE: ${{needs.prepare.outputs.BUILD_DATE}}
+        run: |
+          brew install ninja
+          # Disable zstd and python. Both are available on the runners, but
+          # installed with homebrew, and only available in the native (x86_64)
+          # form. Therefore, autodetection will pick them up, but linking
+          # universal binaries fails as those libraries are unavailable in the
+          # other (arm64) architecture form.
+          export SDKROOT=$(xcrun --show-sdk-path)
+          MACOS_REDIST=1 LLVM_CMAKEFLAGS="-DLLVM_ENABLE_ZSTD=OFF -DLLDB_ENABLE_PYTHON=OFF" ./build-all.sh $(pwd)/install/llvm-mingw --stage2
           .github/workflows/store-version.sh install/llvm-mingw/versions.txt
           ./test-libcxx-module.sh $(pwd)/install/llvm-mingw
           ./run-tests.sh $(pwd)/install/llvm-mingw
