Update to current llvm-mingw files

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,12 +1,19 @@
-name: GitHub Actions Demo
+name: Builds
 on:
   push:
-  #schedule:
-  #  - cron: '40 12 * * *'
+  schedule:
+    - cron: '0 0 * * *'
 
 jobs:
+  # For scheduled builds, get the commit ids of the latest versions to build.
+  #
+  # Doing this as one single job, which then propagates the information further
+  # to the other jobs, so that all build jobs in one workflow builds the exact
+  # same version. This allows trusting builds without assertions enabled
+  # slightly more, when we know a separate build of the same version but with
+  # assertions enabled, has passed some amount of tests.
   get-versions:
-    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/actions-test')
+    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
     runs-on: ubuntu-latest
     steps:
       - name: Touch file
@@ -17,7 +24,7 @@ jobs:
         run: |
           echo LLVM_VERSION=$(git ls-remote https://github.com/llvm/llvm-project.git | grep 'refs/heads/main$' | awk '{print $1}') >> versions
           echo MINGW_W64_VERSION=$(git ls-remote https://github.com/mingw-w64/mingw-w64.git | grep 'refs/heads/master$' | awk '{print $1}') >> versions
-          echo PYTHON_VERSION_MINGW=$(git ls-remote https://github.com/msys2-contrib/cpython-mingw.git | grep 'refs/heads/mingw-v3.9.11$' | awk '{print $1}') >> versions
+          echo PYTHON_VERSION_MINGW=$(git ls-remote https://github.com/msys2-contrib/cpython-mingw.git | grep 'refs/heads/mingw-v3.10.5$' | awk '{print $1}') >> versions
       - uses: actions/upload-artifact@v2
         with:
           name: versions
@@ -33,7 +40,7 @@ jobs:
   # to better catch such bugs early. This makes the first-stage toolchain built
   # here in scheduled builds somewhat slower.
   linux:
-    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/actions-test')
+    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
     needs: [get-versions]
     runs-on: ubuntu-latest
     steps:
@@ -66,7 +73,7 @@ jobs:
 
   # Build a cross compiler for macOS, targeting Windows.
   macos:
-    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/actions-test')
+    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
     needs: [get-versions]
     runs-on: macos-latest
     steps:
@@ -87,7 +94,9 @@ jobs:
           # Building with MACOS_REDIST=1 (building universal binaries) without
           # --disable-lldb fails in Github Actions, because python is available
           # (and gets picked up), but only exists in native form.
-          MACOS_REDIST=1 ./build-all.sh $(pwd)/install/llvm-mingw --disable-clang-tools-extra --disable-lldb
+          # Disable use of zstd too - it's also available, but only in native
+          # form.
+          MACOS_REDIST=1 LLVM_CMAKEFLAGS="-DLLVM_ENABLE_ZSTD=OFF" ./build-all.sh $(pwd)/install/llvm-mingw --disable-clang-tools-extra --disable-lldb
           cd install
           tar -Jcf ../llvm-mingw-macos.tar.xz llvm-mingw
       - uses: actions/upload-artifact@v2
@@ -101,8 +110,8 @@ jobs:
   # environments). The binaries built here rely on the runtime libraries from
   # the host environment (libstdc++ or libc++). No artifacts are stored from
   # these builds, but llvm-mingw's tests are run.
-  msys:
-    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/actions-test')
+  msys2:
+    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
     needs: [get-versions]
     runs-on: windows-latest
     defaults:
@@ -121,7 +130,6 @@ jobs:
           install: >-
             git
             make
-            tar
           pacboy: >-
             toolchain:p
             cmake:p
@@ -149,9 +157,9 @@ jobs:
   # For scheduled builds, the first stage compiler was built with assertions
   # enabled, but this stage is built without assertions - so the end packaged
   # build should be as fast as normal releases (with the intent that the first
-  # stage compiler should build enough code to find many bugs.)
+  # stage compiler should build enough code to find many regressions).
   linux-cross:
-    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/actions-test')
+    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
     needs: [linux]
     runs-on: ubuntu-latest
     strategy:
@@ -166,7 +174,7 @@ jobs:
       - uses: actions/download-artifact@v3
         with:
           name: linux-toolchain
-      - name: Unpacking cross toolchain
+      - name: Unpack cross toolchain
         run: |
           tar -Jxf llvm-mingw-linux.tar.xz
           rm llvm-mingw-linux.tar.xz
@@ -178,11 +186,12 @@ jobs:
           . /opt/llvm-mingw/versions
           echo Building llvm-project $LLVM_VERSION mingw-w64 $MINGW_W64_VERSION cpython-mingw $PYTHON_VERSION_MINGW
           cat /opt/llvm-mingw/versions >> $GITHUB_ENV
+          echo LLDB_MI_PARAMS=--disable-lldb-mi >> $GITHUB_ENV
       - uses: actions/checkout@v2
       - name: Build
         run: |
           sudo apt-get update && sudo apt-get install autoconf-archive ninja-build
-          ./build-cross-tools.sh /opt/llvm-mingw $(pwd)/install/llvm-mingw-${{matrix.arch}} ${{matrix.arch}} --with-python
+          ./build-cross-tools.sh /opt/llvm-mingw $(pwd)/install/llvm-mingw-${{matrix.arch}} ${{matrix.arch}} --with-python $LLDB_MI_PARAMS
           cd install
           zip -9rq ../llvm-mingw-${{matrix.arch}}.zip llvm-mingw-${{matrix.arch}}
       - uses: actions/upload-artifact@v2
@@ -192,9 +201,10 @@ jobs:
             llvm-mingw-${{matrix.arch}}.zip
           retention-days: 7
 
-  # Run llvm-mingw's tests on x86_64 with the cross-built toolchain from above.
+  # Run llvm-mingw's tests on x86_64 (and i686) with the cross-built x86_64
+  # toolchain from above.
   test-toolchain:
-    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/actions-test')
+    if: (github.event_name != 'schedule') || (github.repository == 'mstorsjo/llvm-mingw')
     needs: [linux-cross]
     runs-on: windows-latest
     defaults:
@@ -209,23 +219,22 @@ jobs:
       - uses: actions/download-artifact@v3
         with:
           name: windows-x86_64-toolchain
-      - name: Unpacking toolchain
+      - name: Unpack toolchain
         run: |
           unzip -q llvm-mingw-x86_64.zip
           rm llvm-mingw-x86_64.zip
           mv llvm-mingw-* /llvm-mingw
           echo /llvm-mingw/bin >> $GITHUB_PATH
       - uses: actions/checkout@v2
-      - name: Build
+      - name: Run tests
         run: |
           ./run-tests.sh /llvm-mingw
 
   # Test cross-building ffmpeg for all 4 targeted architectures from linux.
-  # This is done only on scheduled builds, to give them a bit more testing
-  # (for bugs that can be caught by failed asserts in the compiler), to find
-  # such regressions early.
+  # This is done only on scheduled builds, to give them a bit more testing,
+  # to find potential code generation regressions that trigger failed asserts.
   linux-test-cross-build-ffmpeg:
-    if: (github.event_name == 'schedule') && (github.repository == 'mstorsjo/actions-test')
+    if: (github.event_name == 'schedule') && (github.repository == 'mstorsjo/llvm-mingw')
     needs: [linux]
     runs-on: ubuntu-latest
     strategy:
@@ -240,7 +249,7 @@ jobs:
       - uses: actions/download-artifact@v3
         with:
           name: linux-toolchain
-      - name: Unpacking cross toolchain
+      - name: Unpack cross toolchain
         run: |
           tar -Jxf llvm-mingw-linux.tar.xz
           rm llvm-mingw-linux.tar.xz
@@ -251,7 +260,7 @@ jobs:
         with:
           repository: ffmpeg/ffmpeg
           path: ffmpeg
-      - name: Building ffmpeg
+      - name: Build ffmpeg
         run: |
           sudo apt-get update && sudo apt-get install nasm
           mkdir ffmpeg-build
@@ -261,10 +270,10 @@ jobs:
 
   # Test building ffmpeg for natively on x86_64 Windows and run its tests,
   # to find cases of compiler bugs don't show up as failed asserts in the
-  # compiler itslef, but that only show up at runtime. This is only done
+  # compiler itself, but that only show up at runtime. This is only done
   # for scheduled builds.
   test-ffmpeg:
-    if: (github.event_name == 'schedule') && (github.repository == 'mstorsjo/actions-test')
+    if: (github.event_name == 'schedule') && (github.repository == 'mstorsjo/llvm-mingw')
     needs: [linux-cross]
     runs-on: windows-latest
     defaults:
@@ -289,7 +298,7 @@ jobs:
       - uses: actions/download-artifact@v3
         with:
           name: windows-x86_64-toolchain
-      - name: Unpacking toolchain
+      - name: Unpack toolchain
         run: |
           unzip -q llvm-mingw-x86_64.zip
           rm llvm-mingw-x86_64.zip
@@ -300,7 +309,7 @@ jobs:
         with:
           repository: ffmpeg/ffmpeg
           path: ffmpeg
-      - name: Building & testing ffmpeg
+      - name: Build & test ffmpeg
         run: |
           export PATH=/llvm-mingw/bin:$PATH
           mkdir ffmpeg-build
